version: '3'
services:
  app:
    depends_on:
      - mysqldb
    build: .
    environment:
      SPRING_DATASOURCE_URL: "jdbc:mysql://mysqldb:3306/tutorials?useSSl=false"
    ports:
      - "8080:8080"
  mysqldb:
    image: mysql:latest
    env_file:
      - ./.env
    volumes:
      - "./src/main/resources/init.sql:/docker-entrypoint-initdb.d/init.sql"